# Generated by Django 4.1.7 on 2023-04-17 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_phone_no_alter_user_restaurant_name_and_more'),
        ('customer', '0003_order_is_paid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='OrderModel',
        ),
    ]
