# Generated by Django 4.1.7 on 2023-04-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_ordermodel_address_remove_ordermodel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
