# Generated by Django 4.1.7 on 2023-03-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='Name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='Rarea',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='Rlandmark',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='Rstate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='Pincode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='Rcity',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
