# Generated by Django 4.1.7 on 2023-03-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_address_name_address_rarea_address_rlandmark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Website',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
