# Generated by Django 4.1.7 on 2023-03-24 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='Rarea',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='Rcity',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='Rlandmark',
            new_name='landmark',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='Rstate',
            new_name='state',
        ),
    ]
