# Generated by Django 4.1.7 on 2023-03-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_is_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Restaurantname',
            new_name='Restaurant_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_user',
            new_name='is_Customer',
        ),
        migrations.AddField(
            model_name='user',
            name='Phone_no',
            field=models.IntegerField(default=0),
        ),
    ]
