# Generated by Django 4.1.7 on 2023-04-09 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_restaurantname_user_restaurant_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Phone_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Restaurant_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Website',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_Customer',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_restaurant',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Email', models.EmailField(default=True, max_length=254, null=True)),
                ('Website', models.URLField(null=True)),
                ('Address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.address')),
            ],
            options={
                'db_table': 'Restaurant',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.address')),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
    ]
